### ISSUE TITLE
[Question] [Documentation] - Player live file

### ISSUE THREAD

**Issue by Gamemap** [BlueMap-Minecraft/BlueMapWiki#5]
I am using the BlueMap Command Line Tool and would like to display the player's position in my single player world.
I found a player file in the web/live folder and would like to save the data there.
Can you tell me if this is possible and how the data needs to be saved?
Maybe this could be included in the documentation.

**Comment by DreiMu** [comment]
I didn't test it but you should be able to put `{"players":[{"uuid":"your-uuid","name":"your-name","world":"id-of-the-world","position":{"x":your-x-position,"y":your-y-position,"z":your-z-position}}]}` in your players file in the live folder next to the data folder.

**Comment by Gamemap** [comment]
I can see my player in the list, but not on the map and my playerhead isn't loading.
I have testet both uuid`s wich I found on [namemc.com)](namemc.com).

**Comment by DreiMu** [comment]
ahh I think you have to put the playerhead somewhere with the uuid as the name

**Comment by DreiMu** [comment]
> 
> 
> ahh I think you have to put the playerhead somewhere with the uuid as the name

yes you have to put your playerhead as png into `assets/playerheads/` with your uuid as name

**Comment by Gamemap** [comment]
I can see now the playerhead, but it can't see it on the map.
It seems to be grayed out. (Button disabled)

**Comment by DreiMu** [comment]
what did you pit in the world tag in the `players` file?

**Comment by Gamemap** [comment]
render file

id: "1_17"
name: "1.17 Testwelt"
world: "1_17"

player file
{"players":[{"uuid":"4f64bf725a174033b8cdcc9f0a11adb5","name":"_Estragon_","world":"1_17","position":{"x":10,"y":150,"z":200}}]}

**Comment by DreiMu** [comment]
Ahh I see the world tag should be the value of maps.1_17.world in the `data/settings.json`

**Comment by Gamemap** [comment]
Thank you now it is working!

Vielen Dank für deine Hilfe ;)

**Comment by Gamemap** [comment]
@DreiMu Do you know where I can set the highres loading size (renderdistance) when the website is loaded?

**Comment by Gamemap** [comment]
Do you know where I can set the highres loading size (renderdistance) when the website is loaded?

**Comment by DreiMu** [comment]
You would have to change the sourcecode of the website ([here](https://github.com/BlueMap-Minecraft/BlueMapWeb/blob/ce57dfdda5c1599b896038af184dafe746f3543d/src/MapViewer.js#L72)) to do this, I don't see a config file for this

**Comment by Gamemap** [comment]
Ok, thank you!

**Comment by Gamemap** [comment]
> 
> 
> Do you know where I can set the highres loading size (renderdistance) when the website is loaded?

Solution:

1. Open `BLUEMAP-WEBFOLDER\js\app.NUMBER.js`
2. Search for `loadedHiresViewDistance:200`
3. Replace the number.
