### ISSUE TITLE
Suggestieon : Desktop App

### ISSUE THREAD

**Issue by UsernameAdamGits** [BlueMap-Minecraft/BlueMapWiki#84]
Using a web app is good for easy using and things, but a desktop app would be a good option for smoother rendering that doesn't depend on the browser and such, as website infrastructure isn't as powerful as normal desktop rendering stuff. So what I'm suggesting is an optional desktop app for viewing different blue-maps by connecting to the web, getting the map data, and using a possibly faster desktop renderer. It would also be interesting to have functionality to download maps and view them offline in the app.

**Comment by TBlueF** [comment]
Please - as per [contributing guidelines](https://github.com/BlueMap-Minecraft/BlueMap/blob/f6d39fcdb126cb3a0bbf9303cfbb3f8ed71b35c2/.github/CONTRIBUTING.md#suggesting-a-new-feature-or-change) - use our [discords](https://discord.gg/zmkyJa3) #suggestions channel for suggestions
Thank you :)
